config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'registrations' }
  root 'posts#index'
  get '/users/:id', to: 'users#show', as: 'user'
  resources :posts do
    resources :comments, only: %i(create destroy edit update)
    resources :likes, only: %i(create destroy)
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates  :comment, presence: true, length: { maximum: 100 }
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image,   content_type: {
    in: %w(image/jpeg image/gif image/png),
    message: 'この拡張子は無効です',
  },
                      size: {
                        less_than: 5.megabytes,
                        message: 'サイズが大きいです',
                      },
                      presence: true

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w(content)
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      redirect_to @post
      flash[:notice] = 'コメントしました'
    else
      redirect_to @post
      flash[:alert] = 'コメントに失敗しました'
    end
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    redirect_to root_path unless @comment.user == current_user
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.user == current_user
      @comment.update!(comment_params)
      flash[:notice] = 'コメントが更新されました'
    else
      flash[:alert] = 'コメントの更新に失敗しました'
    end
    redirect_to @post
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.user == current_user
      @comment.destroy!
      flash[:notice] = 'コメントが削除されました'
    else
      flash[:alert] = 'コメントの削除に失敗しました'
    end
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :comment)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    else
      flash[:alert] = 'いいねできませんでした'
      redirect_to @post
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.user == current_user
      @like.destroy!
      respond_to :js
    else
      flash[:alert] = 'いいねの削除に失敗しました'
      redirect_to @post
    end
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i(show new create edit update destroy)
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page]).per(6)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      redirect_to root_path
      flash[:notice] = '投稿が保存されました'
    else
      redirect_to root_path
      flash[:alert] = '投稿に失敗しました'
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.user == current_user
      @post.update!(post_params)
      flash[:notice] = '投稿が更新されました'
    else
      flash[:alert] = '投稿の更新に失敗しました'
    end
    redirect_to @post
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.user == current_user
      @post.destroy!
      flash[:notice] = '投稿が削除されました'
    else
      flash[:alert] = '投稿の削除に失敗しました'
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:content, :image)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  before_action :forbid_test_user, only: %i(edit update destroy)

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  def forbid_test_user
    if @user.email == 'test@example.com'
      flash[:notice] = 'テストユーザーのため変更できません'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?

    gravatar_id = Digest::MD5.hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end

  def full_title(page_title)
    base_title = 'Nature-Picture'
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/views/comments/edit.html.slim
- provide(:title, "コメント編集")

= form_with model: [@post, @comment], local: true do |f|
  .form-group.mt-3
    = f.label :comment, 'コメント'
    = f.text_field :comment, value: @comment.comment, class: 'form-control'
  = f.submit "編集", class: "btn btn-primary"

= link_to "削除", post_comment_path(@comment), method: :delete,
data: { confirm: "この投稿を削除します．よろしいですか？" }, class: 'btn btn-danger mt-3'

app/views/layouts/_navbar.html.slim
.navbar.navbar-fixed-top.navbar-expand-md.navbar-light.bg-light
  div.container
    = link_to image_tag("logo.png", class: 'mt-2 mb-2', size: '230x30'), root_path
    nav
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li= link_to "投稿", new_post_path, class: "mr-3"
          li= link_to "投稿一覧", posts_path
          li.dropdown.ml-2
            a[href="#" class="dropdown-toggle" data-toggle="dropdown"]
              | アカウント
              b.caret
            ul.dropdown-menu
              li= link_to "プロフィール", user_path(current_user)
              li= link_to "設定", edit_user_registration_path(current_user)
              li.divider
              li= link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          li= link_to "ログイン", new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title= full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navbar'
    .container
      - if flash[:notice]
        div.alert.alert-info.mt-3
          = flash[:notice]
      - if flash[:alert]
        div.alert.alert-danger.mt-3
          = flash[:alert]
      = yield

app/views/likes/_like.html.slim
th
  - if post.liked_by(current_user).present?
    = link_to "いいね！を取り消す", post_like_path(post.id, post.liked_by(current_user)),
      method: :delete, remote: true
  - else
    = link_to "いいね！する", post_likes_path(post), method: :post,
      remote: true
td
  = like.count
  |  いいね！

app/views/likes/create.js.erb
$('#like-<%= @post.id %>').
  html("<%= j(render partial: 'likes/like', locals: { post: @post, like: @post.likes}) %>");

app/views/likes/destroy.js.erb
$('#like-<%= @post.id %>').
  html("<%= j(render partial: 'likes/like', locals: { post: @post, like: @post.likes}) %>");

app/views/posts/_posts.html.slim
- posts.each do |post|
  .col-md-4.post-list__items__item
    = link_to post_path(post.id) do
      = image_tag post.image, class: 'post-list__items__item__image' if post.image.attached?
      .post-list__items__item_text
        = post.content

app/views/posts/edit.html.slim
- provide(:title, "投稿編集")

= form_with model: @post, local: true do |f|
  .form-group.mt-3
    = f.label :content, 'キャプション'
    = f.text_field :content, class: 'form-control'
  .form-group
    = f.label :image, '画像'
    = f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: 'form-control'
  = f.submit "編集", class: "btn btn-primary"

app/views/posts/index.html.slim
= search_form_for @q, class: 'mt-5 mb-5' do |f|
  .form-group.row
    = f.label :content_cont, 'キャプションから検索', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :content_cont, class: 'form-control w-25'
  .form-group
    = f.submit class: 'btn btn-outline-primary'

.mb-3
  = paginate @posts
  = page_entries_info @posts

.container.post-list
  .row.post-list__items
    = render partial: 'posts', locals: { posts: @posts }

app/views/posts/new.html.slim
- provide(:title, "新規投稿")
= form_with model: @post do |f|
  .form-group.mt-3
    = f.label :content, 'キャプション'
    = f.text_field :content, class: 'form-control'
  .form-group
    = f.label :image, '画像'
    = f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: 'form-control'
  = f.submit "投稿", class: "btn btn-primary"

app/views/posts/show.html.slim
- provide(:title, "投稿詳細")

h1.mt-3 投稿の詳細
h2.mt-3
  = @post.user.name
  |  さんの投稿

.nav.justify-content-end
  = link_to '一覧', root_path, class: 'nav-link'

table.table.table-hover
  tbody
    tr
      th キャプション
      td= @post.content
    tr
      th 画像
      td= image_tag @post.image.variant(resize: "900x900") if @post.image.attached?

    tr id="like-#{@post.id}"
      = render partial: 'likes/like', locals: { post: @post, like: @post.likes}

    tr
      th コメント一覧
      td
        - @comments.each do |c|
          - if c.user == current_user
            li= link_to "#{c.comment}  (編集できます)", edit_post_comment_path(@post.id, c)
          - else
            li= c.comment
    tr
      th 新規コメント作成
      td
        = form_with model: [@post, Comment.new] do |f|
          = f.hidden_field :user_id, value: current_user.id
          = f.hidden_field :post_id, value: @post.id
          = f.text_field :comment, class: "form-control", placeholder: "コメント ...", autocomplete: :off
          = f.submit "コメントする", class: "btn btn-primary mt-3"
    tr
      th 作成日時
      td= @post.created_at.to_s(:datetime_jp)

- if @post.user == current_user
  = link_to '編集', edit_post_path(@post), class: 'btn btn-primary mr-3 mb-3'
  = link_to '削除', @post, method: :delete,
  data: { confirm: "この投稿を削除します．よろしいですか？" }, class: 'btn btn-danger mb-3'

app/views/users/show.html.slim
- provide(:title, "ユーザー詳細")

.profile-wrap
  .row
    .col-md-4.text-center
      = image_tag avatar_url(@user), class: "round-img"
    .col-md-8
      .row
        h1
          = @user.name
        - if @user == current_user
          = link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn"
          button.setting[type="button" data-toggle="modal" data-target="#exampleModal"]
        #exampleModal.modal.fade[tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"]
          .modal-dialog[role="document"]
            .modal-content
              .modal-header
                h5#exampleModalLabel.modal-title
                  | 設定
                button.close[type="button" data-dismiss="modal" aria-label="Close"]
                  span[aria-hidden="true"]
                    | ×
              .list-group.text-center
                = link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action"
                = link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal"
      - if @user == current_user
        .row
          p
            = @user.email